#
name: Automatic doc checks

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'docs/**'   # Only run on changes to the docs directory

  workflow_dispatch:
    # Manual trigger


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation-checks:
    uses: canonical/documentation-workflows/.github/workflows/documentation-checks.yaml@main
    with:
      working-directory: "docs"
      fetch-depth: 0

  # Run Vale with the default Canonical style. Post notes in the PR.
  vale-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.1.1
        with:
          working-directory: "docs"
          vale_flags: "--config=.sphinx/vale.ini"

