name: Vale style checks

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'docs/**'   # Only run on changes to the docs directory

  workflow_dispatch:
    # Manual trigger


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vale-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.1.1
        with:
          files: docs
          vale_flags: "--config=.vale-style.ini"
